permalink: pretty

excerpt_separator: "<!--end excerpt-->"
paginate: 5
paginate_path: "blog/page/:num"

safe: true
lsi: false
pygments: true

static_url: /static/
production_url : http://siggame.github.com
